trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
  - container: staticappsclient
    image: mcr.microsoft.com/appsvc/staticappsclient:stable

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: printenv
  target: host

- script: printenv
  target: staticappsclient  # this task will run in the container 