trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
  - container: staticappsclient
    image: mcr.microsoft.com/appsvc/staticappsclient:stable

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  target: host
  inputs:
    script: 'ls -al'

- task: CmdLine@2
  target: staticappsclient  # this task will run in the container
  inputs:
    script: 'cd /bin/staticsites/ && ./StaticSitesClient upload --verbose True --apiToken 3872425c666b13b1290693a0514cfc274e3ee179aaa0cf174feb75fad815253f-807961cb-ff20-4c7e-abf1-24f0e0461b5300316939'