trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: staticappsclient
    image: mcr.microsoft.com/appsvc/staticappsclient:stable

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  target: host
  inputs:
    script: 'ls -al'

- task: CmdLine@2
  condition: false
  displayName: 'wget packages-microsoft-prod'
  target: staticappsclient
  inputs:
    script: |
      wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

- task: CmdLine@2
  displayName: 'Install dotnet-sdk-3.1'
  target: staticappsclient
  inputs:
    script: |
      wget -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
      mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
      wget https://packages.microsoft.com/config/debian/9/prod.list
      mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
      chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
      chown root:root /etc/apt/sources.list.d/microsoft-prod.list
      apt-get install -y apt-transport-https
      apt-get update
      apt-get install -y dotnet-sdk-3.1

- task: CmdLine@2
  target: staticappsclient
  inputs:
    script: |
      cd /bin/staticsites
      ./StaticSitesClient upload --verbose True --apiToken $(API_TOKEN) --workdir $(Build.SourcesDirectory) --api Api --app Client --outputLocation wwwroot'