trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: staticappsclient
    image: mcr.microsoft.com/appsvc/staticappsclient:stable

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  target: host
  inputs:
    script: 'ls -al'

- task: CmdLine@2
  target: staticappsclient  # this task will run in the container
  inputs:
    script: 'cd /bin/staticsites/ && ./StaticSitesClient upload --verbose True --apiToken $(API_TOKEN) --workdir $(Build.SourcesDirectory) --api Api --app Client --outputLocation wwwroot'